---
name: Test matrix with list of objects

on:
  workflow_dispatch:

jobs:
  thejob:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        - path: /a/b/c
          secret_name: secret1
        - path: /some/another/path
          secret_name: idono

    steps:
      - run:
          echo "path '${{ matrix.path }}'"
          echo "secret '${{ matrix.secret_name }}'"
