---
name: Test matrix with list of objects

on:
  workflow_dispatch:

jobs:
  thejob:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        presets:
          - path: /a/b/c
            secret_name: secret1
          - path: /some/another/path
            secret_name: idono

    steps:
      - run:
          echo "path '${{ matrix.presets.path }}'"
          echo "secret '${{ matrix.presets.secret_name }}'"
