---
name: Test matrix with list of objects

on:
  workflow_dispatch:

jobs:
  thejob:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        presets:
          - path: /tmp
            secret_name: secret1
          - path: /
            secret_name: idono
    defaults:
      run:
        working-directory: ${{ matrix.presets.path }}
    steps:
      - run:
          echo "path '${{ matrix.presets.path }}'"
          echo "secret '${{ matrix.presets.secret_name }}'"
